import {SMenu} from "../modules/surrealism-ui/index.slint";
import { Navigation } from "../globals.slint";

struct MenuData {
    id:string,
    name:string,
    icon:image
}
export component LeftBar inherits Rectangle {
    in-out property <int> wd:menu.width/1px;
    height: 100%;
    clip: false;
    in-out property <[MenuData]> udata:[
        {id:0,name:"Dashboard",icon:@image-url("../modules/surrealism-ui/icons/hamburger-button.svg")},
        {id:1.0,name:"Pentesting",icon:@image-url("../modules/surrealism-ui/icons/source-code.svg")},
        {id:2.0,name:"Wifi Pentesting",icon:@image-url("../modules/surrealism-ui/icons/wifi.svg")},
        {id:3.0,name:"Dns Enum",icon:@image-url("../modules/surrealism-ui/icons/network-tree.svg")},
        {id:4.0,name:"Find",icon:@image-url("../modules/surrealism-ui/icons/iphone.svg")},
    ];
    in-out property <[MenuData]> ddata:[
        {id:10.0,name:"About",icon:@image-url("../modules/surrealism-ui/icons/help.svg")},
        {id:11.0,name:"Settings",icon:@image-url("../modules/surrealism-ui/icons/setting-two.svg")}
    ];

    menu := SMenu {
        menu-data: udata;
        sub-menu-data: ddata;
        active: Navigation.page;
        change(index, data)=>{Navigation.go(data.id.to-float(),data.name)}
        theme:Navigation.theme?Light:Dark;
        active-color: #03fd6b;
    }
}
