import {SMenu} from "../modules/surrealism-ui/index.slint";
import { Navigation } from "../globals.slint";

struct MenuData {
    id:string,
    name:string,
    icon:image
}
export component RightBar inherits Rectangle {
    height: 100%;
    width: menu.width;
    clip: false;
    in-out property <[MenuData]> udata:[
        {id:1,name:"Edit",icon:@image-url("../modules/surrealism-ui/icons/success.svg")},
        {id:2,name:"Add",icon:@image-url("../modules/surrealism-ui/icons/success.svg")},
        {id:3,name:"Remove",icon:@image-url("../modules/surrealism-ui/icons/success.svg")},
    ];
    in-out property <[MenuData]> ddata:[
        {id:5,name:"History",icon:@image-url("../modules/surrealism-ui/icons/success.svg")},
        {id:6,name:"Thrash",icon:@image-url("../modules/surrealism-ui/icons/success.svg")},
    ];

    menu := SMenu {
        menu-data: udata;
        sub-menu-data: ddata;
        icon-box-size: 40px;
        icon-size: 35px;
        width: 40px;
        change(index, data) => {
            Navigation.page=data.id.to-float();
        }
        active-color: #03fd6b;
    }
}
