import {SHeader} from "../modules/surrealism-ui/index.slint";
import {Navigation} from "../globals.slint";
import {Theme} from "../theme.slint";

export component TopHeader inherits SHeader {
        value: [{ label:"ThinkingMinds", value:"1" }, { label:Navigation.page-name, value:"1" }];
        clicked(index,data)=>{Navigation.go(0,"Dashboard");}
        theme:Navigation.theme?Light:Dark;
        font-color: Theme.palette.text;
}