
import { HorizontalBox, VerticalBox, ListView, StandardListView, GroupBox } from "std-widgets.slint";
import { Page } from "page.slint";

export component AccountPage inherits Page {
    title: @tr("Account Settings");
    description: @tr("ListViews can be used to display a list of elements. The StandardListBox is like the default ListView just with a default text based definition of the visual items. Both can be imported from \"std-widgets.slint\"");

    HorizontalBox {
        vertical-stretch: 1;
        GroupBox {
            title: @tr("User Account");

            
        }
    }
}
