
import { Switch, GridBox, ListView, ScrollView, HorizontalBox, VerticalBox, Palette, Button, GroupBox } from "std-widgets.slint";
import {LoginCheck, LoginStatus} from "./login.slint";
import {Theme} from "../theme.slint";
import { Navigation } from "../globals.slint";
import { SSwitch, SText } from "../modules/surrealism-ui/index.slint";


export global AppState {
    callback refresh();
}

export component Page inherits VerticalLayout {
    in property <string> title: "title";
    in property <string> description: "description";
    alignment: LayoutAlignment.start;
    spacing: 10px;
    padding: 10px;

        HorizontalBox {
            if Navigation.history.length>0:
            HorizontalBox{alignment:start;
                Button{text:"<";clicked =>{Navigation.go_back()}}
            }
            
                Text {
                    font-size: 20px;
                    font-weight: 900;
                    vertical-alignment: center;
                    horizontal-alignment: left;
                    text <=> root.title;
                }
            
            // Spacer
            Rectangle { }

                HorizontalBox {
                alignment: end;
                SText {text: "Light";theme: Palette.color-scheme == ColorScheme.dark?Dark:Light;}

                sw:=SSwitch {
                    active: Palette.color-scheme == ColorScheme.dark;
                    theme: Palette.color-scheme == ColorScheme.dark?Dark:Light;
                    clicked(v) => {
                        Palette.color-scheme = v ? ColorScheme.dark : ColorScheme.light;
                    }
                }
                SText {text: "Dark";theme: Palette.color-scheme == ColorScheme.dark?Dark:Light;}

                
            }
            
        }
        @children
    }
