
import { AboutPage } from "about_page.slint";
import { Dashboard } from "dashboard.slint";
import { AccountPage } from "account.slint";
import { SettingsPage } from "settings.slint";
import {Find} from "./find/index.slint";
import {DnsScreen} from "./pentesting/dnsenum/index.slint";
import { Pentesting } from "pentesting.slint";
import { LoginPage,LoginCheck,LoginStatus } from "login.slint";

export { AboutPage, Dashboard, Find,AccountPage, Pentesting ,SettingsPage,LoginPage,LoginCheck,LoginStatus,DnsScreen}